# -------------------------------------------------------------------------
# Generates the modified k-fold cross-validation figure (Figure 8 in the
# paper). Uses cross_validation.py, which requires pre-computed 'Omega<i>.txt'
# matrices generated by dmd.py.
#
# Author: Marco Mignacca
# -------------------------------------------------------------------------

import numpy as np
import matplotlib.pyplot as plt
from cross_validation import cross_validation

# Parameters
num_vids = 20
T = 80
r = 5
p = 20
P = np.arange(0.001, 1.001, 0.001)
k = 4
c = 100
d_star = 30
dim = 426 * 240

# Events matrix: shape (3500, num_vids), 0-based row indexing
frames = np.zeros((3500, num_vids))

frames[756 - T - 1, 0] = 1;   frames[921 - 1, 0] = 1
frames[366 - T - 1, 1] = 1;   frames[648 - 1, 1] = 1
frames[333 - T - 1, 2] = 1;   frames[786 - 1, 2] = 1;   frames[1086 - T - 1, 2] = 1;  frames[1494 - 1, 2] = 1
frames[660 - T - 1, 3] = 1;   frames[966 - 1, 3] = 1;   frames[1365 - T - 1, 3] = 1;  frames[1638 - 1, 3] = 1
frames[393 - T - 1, 4] = 1;   frames[444 - 1, 4] = 1
frames[351 - T - 1, 5] = 1;   frames[567 - 1, 5] = 1;   frames[987 - 1, 5] = 1
frames[477 - T - 1, 6] = 1;   frames[594 - 1, 6] = 1;   frames[621 - 1, 6] = 1
frames[426 - T - 1, 7] = 1;   frames[762 - 1, 7] = 1
frames[543 - T - 1, 8] = 1;   frames[657 - 1, 8] = 1
frames[354 - T - 1, 9] = 1;   frames[876 - 1, 9] = 1;   frames[1590 - 1, 9] = 1;   frames[1617 - T - 1, 9] = 1;  frames[1728 - 1, 9] = 1;  frames[2067 - 1, 9] = 1
frames[423 - T - 1, 10] = 1;  frames[669 - 1, 10] = 1;  frames[1017 - T - 1, 10] = 1; frames[1290 - 1, 10] = 1; frames[1545 - T - 1, 10] = 1; frames[1620 - 1, 10] = 1
frames[759 - T - 1, 11] = 1;  frames[948 - T - 1, 11] = 1; frames[1413 - T - 1, 11] = 1; frames[1836 - T - 1, 11] = 1; frames[1917 - 1, 11] = 1; frames[2175 - 1, 11] = 1; frames[2346 - 1, 11] = 1; frames[2469 - 1, 11] = 1
frames[456 - T - 1, 12] = 1;  frames[720 - T - 1, 12] = 1; frames[1269 - T - 1, 12] = 1; frames[1335 - 1, 12] = 1
frames[327 - T - 1, 13] = 1;  frames[534 - 1, 13] = 1;  frames[987 - T - 1, 13] = 1; frames[1131 - 1, 13] = 1; frames[1479 - T - 1, 13] = 1; frames[1572 - 1, 13] = 1; frames[1617 - T - 1, 13] = 1; frames[1707 - 1, 13] = 1
frames[1269 - 1, 14] = 1;     frames[1296 - 1, 14] = 1; frames[1299 - 1, 14] = 1; frames[1656 - T - 1, 14] = 1; frames[1794 - 1, 14] = 1; frames[2280 - T - 1, 14] = 1; frames[2340 - 1, 14] = 1
frames[180 - T - 1, 15] = 1;  frames[984 - T - 1, 15] = 1; frames[1059 - 1, 15] = 1; frames[1089 - 1, 15] = 1; frames[1572 - T - 1, 15] = 1; frames[1722 - 1, 15] = 1
frames[312 - T - 1, 16] = 1;  frames[573 - T - 1, 16] = 1; frames[888 - T - 1, 16] = 1; frames[1332 - 1, 16] = 1; frames[1671 - 1, 16] = 1; frames[1728 - 1, 16] = 1
frames[132 - T - 1, 17] = 1;  frames[630 - T - 1, 17] = 1; frames[687 - 1, 17] = 1; frames[1107 - 1, 17] = 1; frames[1668 - T - 1, 17] = 1; frames[1725 - 1, 17] = 1; frames[2052 - T - 1, 17] = 1; frames[2109 - 1, 17] = 1; frames[2403 - T - 1, 17] = 1; frames[2559 - 1, 17] = 1; frames[3126 - T - 1, 17] = 1
frames[732 - T - 1, 18] = 1;  frames[1407 - T - 1, 18] = 1; frames[1500 - 1, 18] = 1; frames[1941 - 1, 18] = 1
frames[738 - T - 1, 19] = 1;  frames[822 - T - 1, 19] = 1; frames[981 - 1, 19] = 1; frames[1002 - 1, 19] = 1; frames[1287 - T - 1, 19] = 1; frames[1560 - 1, 19] = 1

# Run cross-validation
optimal_deltas, avg_validation_error, avg_training_error = \
    cross_validation(frames, num_vids, P, k, c, d_star)

print(f'Optimal Thresholds: {optimal_deltas}')
print(f'Average Errors: {avg_validation_error}')

# Plot mean training error curve
mean_train_err = np.mean(avg_training_error, axis=0)
best_idx = np.argmin(mean_train_err)

fig, ax = plt.subplots()
ax.plot(P, mean_train_err, linewidth=2)
ax.scatter(P[best_idx], mean_train_err[best_idx], s=100, zorder=5)
ax.set_xlabel('Threshold Values')
ax.set_ylabel('Error')
ax.set_xlim([0, 1])
ax.set_ylim([0, np.max(mean_train_err) + 10])
ax.tick_params(labelsize=16)

plt.show()
